### ISSUE TITLE
For more security spongycastle -> bouncycastle

### ISSUE THREAD

**Issue by Neustradamus** [snowblossomcoin/channels#32]
For more security, can you change old spongycastle (based on old bouncycastle) to bouncycastle?
- https://www.bouncycastle.org/
- https://www.bouncycastle.org/releasenotes.html
- http://www.bouncycastle.org/latest_releases.html
- https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=bouncy%20castle
- https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=bouncycastle
- https://www.cvedetails.com/vulnerability-list/vendor_id-7637/Bouncycastle.html

**Comment by Neustradamus** [comment]
@fireduck64: Thanks a lot!

**Comment by Neustradamus** [comment]
@fireduck64: Always here :/
Can you look?
- https://github.com/snowblossomcoin/channels/search?q=spongycastle&unscoped_q=spongycastle

**Comment by fireduck64** [comment]
Yeah, spongycastle will be part of the build but not used except on android.

**Comment by Neustradamus** [comment]
@fireduck64: It is not needed!

Currently Bouncy Castle last version is 1.65 and Spongy Castle last version is 1.58.
Spongy Castle is a fork of Bouncy Castle.
Please look previous links :)

Since several years, a lot of projects have already moved from Spongy Castle to Bouncy Castle because the project is dead.

You can see discussion "34" in https://github.com/rtyley/spongycastle/issues.

**Comment by Neustradamus** [comment]
@fireduck64: Thanks for Bouncy Castle 1.68 update!
But there is always one old part here, can you look?
- https://github.com/snowblossomcoin/channels/search?q=spongycastle&unscoped_q=spongycastle

**Comment by fireduck64** [comment]
Blocked by: https://github.com/snowblossomcoin/snowblossom/issues/171

**Comment by Neustradamus** [comment]
@fireduck64: Can you remove latest part of spongycastle?
- https://github.com/snowblossomcoin/channels/search?q=spongycastle&unscoped_q=spongycastle

Can you update bouncycastle to 1.69?
